version: "2"
services:
  test:
    build:
      context: .
      dockerfile: D:\project\testNext15\next15testapp\dockerfile.txt
    image: phunguyen1211/test:v2
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "10"
    ports:
      # - "80:3000"
      - "3000:3000"
    restart: "always"
    networks:
      - app
networks:
  app:
    driver: bridge
