apiVersion: v1
kind: Service
metadata:
  #The name of the Kubernetes Service to be created 
  #in the Kubernetes cluster
  name: next-app-service 
spec:
  selector:
    app: next-app 
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 8081 #Service port
    targetPort: 8081 #The port for the React.js application container